version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASS}
      TZ: "Europe/Warsaw"
    volumes:
      - .:/app
      - ./logs:/app/logs  # For logs file
    ports:
      - "8000:8000"

volumes:
  db_data:
